1) Write python code from scratch to find error metrics of deep learning model. Actual
values and deep learning model predicted values are shown in Table 1. Also compare the results
with outcome of libraries

YActual YP red
20 20.5
30 30.3
40 40.2
50 50.6
60 60.7
Tabela 1: YActual Vs. YP red

In [ ]:
y_actual = [20, 30, 40, 50, 60]
y_pred = [20.5, 30.3, 40.2, 50.6, 60.7]

n = len(y_actual)
mae = sum(abs(ya - yp) for ya, yp in zip(y_actual, y_pred)) / n
mse = sum((ya - yp) ** 2 for ya, yp in zip(y_actual, y_pred)) / n
rmse = mse ** 0.5

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)

Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127


With libraries.

In [ ]:
import numpy as np

y_actual = np.array([20, 30, 40, 50, 60])
y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

mae=np.mean(np.abs(y_actual - y_pred))
mse=np.mean((y_actual - y_pred)**2)
rmse=np.sqrt(mse)
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)

Mean Absolute Error: 0.4600000000000016
Mean Squared Error: 0.24600000000000147
Root Mean Squared Error: 0.49598387070549127


2) Write python code from scratch to find evaluation metrics of deep learning model.
Actual values and deep learning model predicted values are shown in Table 2. Also compare the
results with outcome of libraries

YActual YP red
0 0 1 1 2 0
0 0 1 0 2 0
0 1 1 2 2 1
0 2 1 0 2 2
0 2 1 2 2 2
Tabela 2: YActual Vs. YP red

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_actual = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
y_pred = [0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2]

cm = confusion_matrix(y_actual, y_pred)
print("Confusion Matrix:")
print(cm)

accuracy = accuracy_score(y_actual, y_pred)
print("\nAccuracy:", accuracy)
precision = precision_score(y_actual, y_pred, average=None)
recall = recall_score(y_actual, y_pred, average=None)
f1 = f1_score(y_actual, y_pred, average=None)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
precision_overall = precision_score(y_actual, y_pred, average='macro')
recall_overall = recall_score(y_actual, y_pred, average='macro')
f1_overall = f1_score(y_actual, y_pred, average='macro')

print("\nOverall Precision (Macro):", precision_overall)
print("Overall Recall (Macro):", recall_overall)
print("Overall F1 Score (Macro):", f1_overall)

Confusion Matrix:
[[2 1 2]
 [2 1 2]
 [2 1 2]]

Accuracy: 0.3333333333333333
Precision: [0.33333333 0.33333333 0.33333333]
Recall: [0.4 0.2 0.4]
F1 Score: [0.36363636 0.25       0.36363636]

Overall Precision (Macro): 0.3333333333333333
Overall Recall (Macro): 0.3333333333333333
Overall F1 Score (Macro): 0.32575757575757575
